controller:
  admin:
    username: admin
    password: admin123

  serviceType: LoadBalancer
  servicePort: 80
  service:
    port: 80
    targetPort: 8080

  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "250m"
      memory: "512Mi"

  persistentVolume:
    enabled: true
    storageClass: ""
    size: 10Gi

  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest
    - credentials-binding:latest
    - github:latest
    - docker-plugin:latest
    - docker-workflow:latest
    - job-dsl:latest

  serviceAccount:
    name: jenkins-sa
    create: false

  JCasC:
    configScripts:
      credentials: |
        credentials:
          system:
            domainCredentials:
              - credentials:
                  - usernamePassword:
                      scope: GLOBAL
                      id: github-token
                      username: Art_of_D # GitHub username
                      password: github_pat_<token> # GitHub PAT
                      description: GitHub PAT
      seed-job: |
        jobs:
          - script: >
              job('seed-job') {
                description('Job to generate pipeline for Django project')
                scm {
                  git {
                    remote {
                      url('<https://github.com/AndriyDmitriv/infra.git>') # GitHub repository
                      credentials('github-token')
                    }
                    branches('*/main')
                  }
                }
                steps {
                  dsl {
                    text('''
                      pipelineJob("django-pipeline") {
                        definition {
                          cpsScm {
                            scm {
                              git {
                                remote {
                                  url("<https://github.com/AndriyDmitriv/infra.git>") # GitHub repository
                                  credentials("github-token")
                                }
                                branches("*/main")
                              }
                            }
                          }
                        }
                      }
                    ''')
                  }
                }
              }
