{{- if .Values.config.POSTGRES_PASSWORD }}
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.config.POSTGRES_PASSWORD | quote }}
{{- end }}